## IMPORT

Import serve a importare Moduli (singolo file .py) o pacchetti ( insieme di file .py).

Il modulo ch eimportiamo deve esistere nel sistema in cui stiamo lavorando

In [24]:
import turtle  # importo il modulo turtle che sta fuori da qui

# se faccio questo non funziona
donatello = Turtle()

NameError: name 'Turtle' is not defined

In [ ]:
# devo fare cosi
import turtle as t

raffaello = t.Turtle()

In [ ]:
# oppure importare singole classi/funzioni all'interno del modulo
from turtle import Turtle
raffaello = turtle()

TypeError: 'module' object is not callable

In [ ]:
import numpy
import math

print( math.sqrt(4))
print( numpy.sqrt([4,9,25]))

2.0
[2. 3. 5.]


## NUMPY

è il pacchetto che consente di lavorare con i vettori!! Fondamentale in dataScience

In [ ]:
import numpy as np

vettore = np.array([1,2,3,4,5])
print(vettore)
print(type(vettore))

matrice = np.array([[0,0,0,1,0,0,0,0],
                    [0,0,0,0,0,0,1,0],
                    [0,1,0,0,0,0,0,0],
                    [0,0,0,0,0,0,1,0],
                    [0,0,0,0,0,0,1,0],
                    [0,0,0,0,0,0,1,0],
                    [0,0,0,0,0,0,1,0],
                    [0,0,0,0,0,0,1,0]])

print(matrice)
                   

[1 2 3 4 5]
<class 'numpy.ndarray'>
[[0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 0]]


In [ ]:
v = np.array([1,2,3,4,5])
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

#np.size(v)
#np.shape(v)
np.size(a)
#np.shape(a)

4

In [ ]:
np.max(v)
np.mean(v)
np.std(v)

1.4142135623730951

In [ ]:
np.transpose(a)

array([[1, 3],
       [2, 4]])

In [ ]:
a + b

array([[ 6,  8],
       [10, 12]])

In [ ]:
np.inner(a,b) # Prodotto scalare 

array([[17, 23],
       [39, 53]])

## Matplotlib

visualizzare statistiche animate e interattive